# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: '<a href="https://shazstar.github.io/">Home page.</a>'

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
