# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: Copyright 2020 ShazStar. // <a href="https://shazstar.github.io/">Home page.</a>

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # true or false (default)

title: ShazStar. // Blog.
description: ShazStar's personal blog.

plugins:
  - jekyll-seo-tag
