# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - tags.html
  - categories.html
  - about.md

footer: Copyright 2020-2025 ShazStar. // <a href="/feed.xml">RSS.</a> // <a href="https://shazstar.github.io/">Home page.</a>

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # true or false (default)

title: ShazStar. // Blog.
description: ShazStar's personal blog.
url: https://shazstar.github.io/blog

plugins:
  - jekyll-seo-tag