# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - tags.html
  - categories.html
  - feed.xml
  - about.md

footer: Copyright 2020-2025 ShazStar. // <a href="https://shazstar.github.io">Home page.</a> // <a href="https://shazstar.github.io/twblog">中文Blog.</a>

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # true or false (default)

title: ShazStar. // Blog.
description: ShazStar's personal blog.
url: https://shazstar.github.io/blog

plugins:
  - jekyll-seo-tag